
export const SET_ALERT                      = "SET_ALERT";

export const GET_DIRECTORY_TIME_SUCCESS     = "GET_DIRECTORY_TIME_SUCCESS";
export const GET_DIRECTORY_TIME_ERROR       = "GET_DIRECTORY_TIME_ERROR";

export const GET_MASTERS_SUCCESS            = "GET_MASTERS_SUCCESS";
export const GET_MASTERS_ERROR              = "GET_MASTERS_ERROR";

export const GET_DIRECTORY_SERVICES_SUCCESS = "GET_DIRECTORY_SERVICES_SUCCESS";
export const GET_DIRECTORY_SERVICES_ERROR   = "GET_DIRECTORY_SERVICES_ERROR";

export const CREATE_REGISTER_SUCCESS        = "CREATE_REGISTER_SUCCESS";
export const CREATE_REGISTER_ERROR          = "CREATE_REGISTER_ERROR";

export const CHANGE_SCHEDULE_DATA           = "CHANGE_SCHEDULE_DATA";
export const CHANGE_SERVICE_DATA            = "CHANGE_SERVICE_DATA";
export const CHANGE_CLIENT_DATA             = "CHANGE_CLIENT_DATA";
